language: c
addons:
  apt:
    packages:
    - libasound2:i386
    - lib32z1
    - lib32bz2-1.0
    - libssl1.0.0:i386
    - libfreetype6:i386
script:
- if [[ ${TRAVIS_BRANCH} == "master" ]]; then make deploy; fi
env:
  global:
  - secure: f5eEGDhuGzDq7i4qvzL/CYV/tDFpgZVUfKTNRR3CCJV+eHDtzSEb0uEjqKo+tRSaeDl7de9CVkR6A3NL6Ykw/ehZMtOaMzJAwbH1Psnwac+49Y8crcMFXAI5/FzwzNtm2xvmtzr0C9aVzU9xwTAlmm3JHNvPYj5NiUgBOPbLKMqrGWxWAX/dApc74JeR33FwDjA3SOmnLRiv7IID4cL3O6LluYvTNL55BkBzzODnKEsWtFe9iRt6K4dn1MaXY89KHvY06CLNqptuzEi8W6i/TgFfRMtm0jvcgzRvF4NJQfNrxzeh7Pb3bam0tXnIgrUDpUKBPf0dl1QMJuLc9h1mp5s56Iz21p7gYhs2RvYr/amIWksdZE7xoD2pp45W96jA32fxxgQ42sM6F4e4k22yVvdM+n045qzURYtBvZQn3QIkSsPDCS9ZinZBUfhqzZ4XH4iaELSNnMlqTQI6JavzJ2qv60OXfqroSTYP9QGYUPdqrX3QG38xPNMd51phOKEFizg58lkAapIK7G3W8+TeXuOn6jUxhExg38EIMVWfN4h45JEU0TpQWNX6AFK1vRh0JR3YWyL/eQ8A8Q8t6Xzh0wD9MatPMxClHdgtjCNbuJ5X+fdEoaVsm4Id+dNGdtFJ2rwGpAoh4kAjPIoHK2XK60T4Mw3BrvSzhrAfxJ5546w=
